<?php

declare(strict_types=1);

$host = getenv('DB_HOST') ?: '127.0.0.1';
$port = getenv('DB_PORT') ?: '3306';
$db = getenv('DB_DATABASE') ?: 'itstackpr_local';
$user = getenv('DB_USERNAME') ?: 'root';
$pass = getenv('DB_PASSWORD') ?: '';
$out = $argv[1] ?? __DIR__ . '/../database/itstackpr_export.sql';

$pdo = new PDO(
    "mysql:host={$host};port={$port};dbname={$db};charset=utf8mb4",
    $user,
    $pass,
    [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]
);

$fh = fopen($out, 'wb');
if ($fh === false) {
    fwrite(STDERR, "Cannot write output file: {$out}\n");
    exit(1);
}

$write = static function (string $line) use ($fh): void {
    fwrite($fh, $line . PHP_EOL);
};

$write('-- SQL dump generated by scripts/export_mysql_dump.php');
$write('-- Database: ' . $db);
$write('-- Date: ' . date('Y-m-d H:i:s'));
$write('SET NAMES utf8mb4;');
$write('SET FOREIGN_KEY_CHECKS = 0;');
$write('');

$tables = $pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);

foreach ($tables as $table) {
    $tableName = (string) $table;
    $row = $pdo->query("SHOW CREATE TABLE `{$tableName}`")->fetch();
    $createSql = $row['Create Table'] ?? null;
    if ($createSql === null) {
        continue;
    }

    $write("-- ----------------------------");
    $write("-- Table structure for `{$tableName}`");
    $write("-- ----------------------------");
    $write("DROP TABLE IF EXISTS `{$tableName}`;");
    $write($createSql . ';');
    $write('');

    $rows = $pdo->query("SELECT * FROM `{$tableName}`")->fetchAll();
    if (count($rows) === 0) {
        continue;
    }

    $write("-- ----------------------------");
    $write("-- Records of `{$tableName}`");
    $write("-- ----------------------------");

    foreach ($rows as $data) {
        $columns = array_map(
            static fn (string $col): string => "`{$col}`",
            array_keys($data)
        );

        $values = array_map(
            static function ($value) use ($pdo): string {
                if ($value === null) {
                    return 'NULL';
                }

                if (is_bool($value)) {
                    return $value ? '1' : '0';
                }

                if (is_int($value) || is_float($value)) {
                    return (string) $value;
                }

                return $pdo->quote((string) $value);
            },
            array_values($data)
        );

        $write(
            'INSERT INTO `' . $tableName . '` (' .
            implode(', ', $columns) .
            ') VALUES (' .
            implode(', ', $values) .
            ');'
        );
    }

    $write('');
}

$write('SET FOREIGN_KEY_CHECKS = 1;');
fclose($fh);

echo "Dump created: {$out}" . PHP_EOL;
